# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1662f42e686802fffa3fe71102417a3651db09b39e4333ff3627f3d3b7de90f614f9f93ec80fe41752cba882b4c1e00f7b88a72707399909f6019233ff2eca24

test:
  secret_key_base: 3090e37ae929ef94ab02ed249dc8dbef62cb66723359b89c3046a5bc09fc7deace367ead00bf188779c5ec2476c0e3b7628a3eb82d3d7d03a8b9738463d3ad77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
